version: '3.7'

services:
  substore:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: SubStore
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./data/sub-store.json:/release/sub-store.json
      - ./data/root.json:/release/root.json