name: Sub-Store
description: "æ”¯æŒ Surge æ­£å¼ç‰ˆçš„å‚æ•°è®¾ç½®åŠŸèƒ½. æµ‹è½åœ°åŠŸèƒ½ ability: http-client-policy, åŒæ­¥é…ç½®çš„å®šæ—¶ cronexp: 55 23 * * *"
compat_arguments:
  ability: http-client-policy
  cronexp: 55 23 * * *
  sync: '"Sub-Store Sync"'
  timeout: "120"
  engine: auto
  produce: '"# Sub-Store Produce"'
  produce_cronexp: 50 */6 * * *
  produce_sub: '"sub1,sub2"'
  produce_col: '"col1,col2"'
compat_arguments_desc: '\n1ï¸âƒ£ ability\n\né»˜è®¤å·²å¼€å¯æµ‹è½åœ°èƒ½åŠ›\néœ€è¦é…åˆè„šæœ¬æ“ä½œ\nå¦‚ https://raw.githubusercontent.com/Keywos/rule/main/cname.js\nå¡«å†™ä»»æ„å…¶ä»–å€¼å…³é—­\n\n2ï¸âƒ£ cronexp\n\nåŒæ­¥é…ç½®å®šæ—¶ä»»åŠ¡\né»˜è®¤ä¸ºæ¯å¤© 23 ç‚¹ 55 åˆ†\n\nå®šæ—¶ä»»åŠ¡æŒ‡å®šæ—¶å°†è®¢é˜…/æ–‡ä»¶ä¸Šä¼ åˆ°ç§æœ‰ Gist. åœ¨å‰ç«¯, å«åš ''åŒæ­¥'' æˆ– ''åŒæ­¥é…ç½®''\n\n3ï¸âƒ£ sync\n\nè‡ªå®šä¹‰å®šæ—¶ä»»åŠ¡å\nä¾¿äºåœ¨è„šæœ¬ç¼–è¾‘å™¨ä¸­é€‰æ‹©\nè‹¥è®¾ä¸º # å¯å–æ¶ˆå®šæ—¶ä»»åŠ¡\n\n4ï¸âƒ£ timeout\n\nè„šæœ¬è¶…æ—¶, å•ä½ä¸ºç§’\n\n5ï¸âƒ£ engine\n\né»˜è®¤ä¸ºè‡ªåŠ¨ä½¿ç”¨ webview å¼•æ“, å¯è®¾ä¸ºæŒ‡å®š jsc, ä½† jsc å®¹æ˜“çˆ†å†…å­˜\n\n6ï¸âƒ£ produce\n\nè‡ªå®šä¹‰å¤„ç†è®¢é˜…çš„å®šæ—¶ä»»åŠ¡å\nä¸€èˆ¬ç”¨äºå®šæ—¶å¤„ç†è€—æ—¶è¾ƒé•¿çš„è®¢é˜…, ä»¥æ›´æ–°ç¼“å­˜\nè¿™æ · Surge ä¸­æ‹‰å–çš„æ—¶å€™å°±èƒ½ç”¨åˆ°ç¼“å­˜, ä¸è‡³äºæ€»æ˜¯è¶…æ—¶\nè‹¥è®¾ä¸º # å¯å–æ¶ˆæ­¤å®šæ—¶ä»»åŠ¡\né»˜è®¤ä¸å¼€å¯\n\n7ï¸âƒ£ produce_cronexp\n\né…ç½®å¤„ç†è®¢é˜…çš„å®šæ—¶ä»»åŠ¡\n\né»˜è®¤ä¸ºæ¯ 6 å°æ—¶\n\n9ï¸âƒ£ produce_sub\n\nè‡ªå®šä¹‰éœ€å®šæ—¶å¤„ç†çš„å•æ¡è®¢é˜…å\nå¤šä¸ªç”¨ , è¿æ¥\n\nğŸ”Ÿ produce_col\n\nè‡ªå®šä¹‰éœ€å®šæ—¶å¤„ç†çš„ç»„åˆè®¢é˜…å\nå¤šä¸ªç”¨ , è¿æ¥\n\nâš ï¸ æ³¨æ„: æ˜¯ åç§°(name) ä¸æ˜¯ æ˜¾ç¤ºåç§°(displayName)\nå¦‚æœåç§°éœ€è¦ç¼–ç , è¯·ç¼–ç åå†ç”¨ , è¿æ¥\né¡ºåº: å¹¶å‘æ‰§è¡Œå•æ¡è®¢é˜…, ç„¶åå¹¶å‘æ‰§è¡Œç»„åˆè®¢é˜…'
scriptings:
  - http_request:
      name: Sub-Store Core
      match: ^https?:\/\/sub\.store\/((download)|api\/(preview|sync|(utils\/node-info)))
      script_url: https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-1.min.js
      body_required: true
  - http_request:
      name: Sub-Store Simple
      match: ^https?:\/\/sub\.store
      script_url: https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-0.min.js
      body_required: true
  - schedule:
      name: "{{{sync}}}"
      cron: "{{{cronexp}}}"
      script_url: https://github.com/sub-store-org/Sub-Store/releases/latest/download/cron-sync-artifacts.min.js
  - schedule:
      name: "{{{produce}}}"
      cron: "{{{produce_cronexp}}}"
      script_url: https://github.com/sub-store-org/Sub-Store/releases/latest/download/cron-sync-artifacts.min.js
      arguments:
        _compat.$argument: '"sub={{{produce_sub}}}&col={{{produce_col}}}"'
mitm:
  hostnames:
    includes:
      - sub.store
